source 'https://rubygems.org'

gem 'rails', '~> 3.2.11'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

gem 'json'
gem 'test-unit'

# Last version that worked on Ruby 1.8
gem 'i18n', '~> 0.6.0'

gem 'union_station_hooks_core', :path => 'ush_core'
gem 'union_station_hooks_rails', :path => 'ush_rails'
